version: '3'

services:
  app:
    build: ./
    container_name: app
    volumes:
      - ./docker.config/php/www.conf:/usr/local/etc/php-fpm.d/pool.conf
      - ./source:/var/www/html
    restart: always

  nginx:
    image: nginx:1.15.7
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./docker.config/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./docker.config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./source:/var/www/html
    depends_on:
      - app
    restart: always
